name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  unit-test:
    name: "Unit Test"
    uses: na4ma4/actions/.github/workflows/unit-test.yml@main
    with:
      enable-codecov: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  goreleaser:
    name: "Goreleaser"
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - unit-test
    uses: na4ma4/actions/.github/workflows/goreleaser.yml@main
    secrets:
      GO_RELEASER_GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
